### ISSUE TITLE
Is there any kind of documentation on this / any documentation planned? Want to be able to test this.

### ISSUE THREAD

**Issue by loughreykian** [skui-org/skui#1]

**Comment by rubenvb** [comment]
No, I haven't started on any documentation.

The furthest I've gotten is the widget_gallery example, and I plan to expand its functionality first, which means adding all sorts of widgets and a way to handle styling in order to emulate various platforms etc.

This is very much a WIP though, I can help you get it all set up if you want to experiment with it.

**Comment by rubenvb** [comment]
Well, basically all you need to do is
```
git clone git@github.com:skui-org/skui.git
git submodule update --init --recursive
mkdir build && cd build
cmake ..
cmake --build .
ctest
```
You might need to pass a specific generator to CMake though. You can check out the Appveyor or Travis builds for more information. The logs there should contain all the build commands along with all their output.

**Comment by loughreykian** [comment]
looks like when trying to clone the repository, it says I don't have access to it.

**Comment by rubenvb** [comment]
Right, I gave you the SSH URL, you should see the https url on the repository page:
```
https://github.com/skui-org/skui.git
```

**Comment by rubenvb** [comment]
What are the exact details of your setup (OS, compiler, cmake version, generator, etc.)?

**Comment by rubenvb** [comment]
Please contact me directly if you're still interested.
